// Generated by https://quicktype.io

export interface Pokemon {
  
  id:                       number;
 
  name:                     string;
 
  sprites:                  Sprites;
  
}




export interface Sprites {
  back_default:       string;
  back_female:        null;
  back_shiny:         string;
  back_shiny_female:  null;
  front_default:      string;
  front_female:       null;
  front_shiny:        string;
  other?:             Other;
}

export interface Other {
  dream_world:        DreamWorld;
}

export interface DreamWorld {
  front_default: string;
  front_female:  null;
}
